<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<?php if($this->getProductData()->getId()): ?>
    <div class="page-head">
        <h4><?php echo $this->__('Review Details') ?></h4>
    </div>
    <div class="my-review-detail">
        <div class="product-image">
            <p><a href="<?php echo $this->getProductData()->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProductData(), 'small_image')->resize(125, 125); ?>" alt="<?php echo $this->htmlEscape($this->getProductData()->getName()) ?>" height="100" width="100" /></a></p>
            <?php if( $this->getRating() && $this->getRating()->getSize()): ?>
                <small><?php echo $this->__('Average Customer Rating') ?>:</small>
                <?php echo $this->getReviewsSummaryHtml($this->getProductData()) ?>
            <?php endif; ?>
        </div>
    <div class="details">
        <h3><?php echo $this->htmlEscape($this->getProductData()->getName()) ?></h3>
        <?php if( $this->getRating() && $this->getRating()->getSize()): ?>
        <strong><?php echo $this->__('Product Rating:') ?></strong>
            <?php foreach ($this->getRating() as $_rating): ?>
            <?php if($_rating->getPercent()): ?>
                <div class="ratings">
                   <?php echo $this->__($_rating->getRatingCode()) ?>
                    <div class="rating-box">
                        <div class="rating" style="width:<?php echo ceil($_rating->getPercent()) ?>%;"></div>
                    </div>
                </div>
            <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
        <div class="clear"></div>
        <?php echo $this->__('Product Review (submitted on %s):', $this->dateFormat($this->getReviewData()->getCreatedAt())) ?>
            <div class="description">
                <p><?php echo nl2br($this->htmlEscape($this->getReviewData()->getDetail())) ?></p>
            </div>
    </div></div>
    <div class="button-set"><a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back to Product Reviews') ?></a></div><br />
<?php endif; ?>
