<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<?php 
/**
 * @see Mage_Page_Block_Template_Container
 */
?>
<div class="page-head">
    <h3><?php echo $this->getTitle() ?></h3>
</div>
<?php echo $this->getChildHtml() ?>
