<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php $_links = $this->getLinks(); ?>
<?php if(count($_links)>0): ?>
<div id="footer_link">
       <ul class="footerbar" <?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
            <?php foreach($_links as $_link): ?>
                <li <?php if($_link->getIsFirst()): ?> class="first"<?php elseif($_link->getIsLast()): ?> class="last"<?php endif; ?><?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?> <?php if($_link->getIsLast()){?> style="border-right:none;padding-right:0px;" <? } ?> >
                <?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
            <?php endforeach; ?>
        </ul>
</div>
<?php endif; ?>

