<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>

<?php $_items = $this->getReviewsCollection()->getItems();?>
<?php if (count($_items)):?>
<div class="collateral-box dedicated-review-box" id="customer-reviews">
    <div class="head">
        <h4><?php echo $this->__('Customer Reviews') ?></h4>
    </div>

    <?php echo $this->getChildHtml('toolbar') ?>

    <ol style="margin-top:15px;">
        <?php foreach ($_items as $_review):?>
            <li>
                <a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><strong><?php echo $this->htmlEscape($_review->getTitle()) ?></strong></a> <?php echo $this->__('Review by %s', $this->htmlEscape($_review->getNickname())) ?>
                <table class="ratings-list" cellspacing="0">
                    <tbody>
                        <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                        <tr>
                            <td class="label"><strong><?php echo $_vote->getRatingCode() ?></strong></td>
                            <td>
                                <div class="rating-box">
                                    <div class="rating" style="width: <?php echo $_vote->getPercent() ?>%;"></div>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <p><?php echo nl2br($this->htmlEscape($_review->getDetail())) ?> <?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?></p>
            </li>
        <?php endforeach; ?>
    </ol>

    <?php echo $this->getChildHtml('toolbar') ?>
</div>
<?php endif;?>

<br/>

<?php echo $this->getChildHtml('review_form') ?>
