<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<?php if($pageData->getPageMetaKeywords()): ?>
<meta name="keywords" content="<?php echo $pageData->getPageMetaKeywords() ?>" />
<?php endif; ?>
<?php if($pageData->getPageMetaDescription()): ?>
<meta name="description" content="<?php echo $pageData->getPageMetaDescription() ?>" />
<?php endif; ?>
