<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/

/**
USAGE:

Simple:

<?php echo $this->getLayout()->createBlock('customer/widget_dob')
   ->setDate($this->getCustomer()->getDob())
   ->toHtml() ?>

For checkout/onepage/billing.phtml:

<?php echo $this->getLayout()->createBlock('customer/widget_dob')
   ->setDate($this->getCustomer()->getDob())
   ->setFieldIdFormat('billing:%s')
   ->setFieldNameFormat('billing[%s]')
   ->toHtml() ?>

NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css
      Alternatively we could calculate widths automatically using block input parameters.
*/
?>
<div class="customer-dob">
    <label for="<?php echo $this->getFieldId('day')?>">
        <?php echo $this->__('Date of Birth') ?>
        <?php if ($this->isRequired()):?><span class="required">*</span><?php endif ?>
    </label>

    <div class="input-box dob-day">
        <input type="text" id="<?php echo $this->getFieldId('day')?>" name="<?php echo $this->getFieldName('day')?>" value="<?php echo $this->getDay() ?>" title="<?php echo $this->__('Day') ?>" class="input-text validate-custom" <?php echo $this->getFieldParams() ?> />
        <label for="<?php echo $this->getFieldId('day')?>" class="label-dob"><?php echo $this->__('DD') ?></label>
    </div>

    <div class="input-box dob-month">
        <input type="text" id="<?php echo $this->getFieldId('month')?>" name="<?php echo $this->getFieldName('month')?>" value="<?php echo $this->getMonth() ?>" title="<?php echo $this->__('Month') ?>" class="input-text validate-custom" <?php echo $this->getFieldParams() ?> />
        <label for="<?php echo $this->getFieldId('month')?>" class="label-dob"><?php echo $this->__('MM') ?></label>
    </div>

    <div class="input-box dob-year">
        <input type="text" id="<?php echo $this->getFieldId('year')?>" name="<?php echo $this->getFieldName('year')?>" value="<?php echo $this->getYear() ?>" title="<?php echo $this->__('Year') ?>" class="input-text validate-custom" <?php echo $this->getFieldParams() ?> />
        <label for="<?php echo $this->getFieldId('year')?>" class="label-dob"><?php echo $this->__('YYYY') ?></label>
    </div>

    <div class="dob-full" style="display:none;">
        <input type="hidden" id="<?php echo $this->getFieldId('dob')?>" name="<?php echo $this->getFieldName('dob')?>" />
    </div>

    <div style="opacity: 0.999999; display:none;" class="validation-advice"></div>
</div>
<script type="text/javascript">
//<![CDATA[
    var customer_dob = new Varien.DOB('.customer-dob', <?php echo $this->isRequired() ? 'true' : 'false' ?>, '<?php echo $this->getDateFormat() ?>');
//]]>
</script>
