<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
?>

<div id="familyImage" class="alpha"><?php echo $this->getChildHtml('media') ?>
</div>
<div class="fiveFifty alpha omega">
<form action="<?php echo $this->getAddToCartUrl($_product) ?>"
	method="post" id="product_addtocart_form"
	<?php if($_product->getOptions()): ?> enctype="multipart/form-data"
	<?php endif; ?>><?php echo $_helper->productAttribute($_product, $this->htmlEscape($_product->getName()), 'name') ?>

<div class="clear"></div>

	<?php echo $this->getReviewsSummaryHtml($_product, false, false)?>
<fieldset class="no-display"><input type="hidden" name="product"
	value="<?php echo $_product->getId() ?>" /> <input type="hidden"
	name="related_product" id="related-products-field" value="" /></fieldset>
	<?php echo $this->getChildHtml('alert_urls') ?> <?php echo $this->getChildHtml('product_type_data') ?>
	<?php if (!$this->hasOptions()):?>
<div class="add-to-holder"><?php if($_product->isSaleable()): ?> <?php echo $this->getChildHtml('addtocart') ?>
	<?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
<span class="add-or"><?php echo $this->__('OR') ?></span> <?php endif; ?>
<?php endif; ?> <?php echo $this->getChildHtml('addto') ?></div>
<?php else:?> <?php echo $this->getChildHtml('addto') ?> <?php endif; ?>
<div class="divider"></div>
<?php if ($_product->getShortDescription()):?> <br />
<p class="bold"><strong><?php echo $this->__('Quick Overview') ?></strong></p>
<div class="short-description"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
</div>
<?php endif;?> <?php echo $this->getChildHtml('other');?> <?php if ($_product->isSaleable() && $this->hasOptions()):?>
<?php echo $this->getChildChildHtml('container1', '', true, true) ?> <?php endif;?>
<div class="clear"></div>
<?php if ($_product->isSaleable() && $this->hasOptions()):?> <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
<?php endif;?> <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
</form>
<script type="text/javascript">
						var productAddToCartForm = new VarienForm('product_addtocart_form');
						productAddToCartForm.submit = function(){
						if (this.validator.validate()) {
						this.form.submit();
						}
						}.bind(productAddToCartForm);
					</script>

</form>

<div class="product-collateral"><?php if ($_description = $this->getChildHtml('description')):?>
<div class="collateral-box">
<div class="head">
<h4><?php echo $this->__('Product Description') ?></h4>
</div>
<?php echo $_description ?></div>
<?php endif;?> <?php if ($_additional = $this->getChildHtml('additional')):?>
<div class="collateral-box">
<div class="head">
<h4><?php echo $this->__('Additional Information') ?></h4>
</div>
<?php echo $_additional ?></div>
<?php endif;?> <?php echo $this->getChildHtml('upsell_products') ?> <?php echo $this->getChildHtml('product_additional_data') ?>
</div>