<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
?>

	<div id="familyImage" class="alpha">
		<?php echo $this->getChildHtml('media') ?>
	</div>
	<div class="fiveFifty alpha omega">
		<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
		<div>
			<p id="familyDescription">
				<span id="familyTitle" class="title">
	    			<?php echo $_helper->productAttribute($_product, $this->htmlEscape($_product->getName()), 'name') ?>
	    		</span>
	    		<span id="familyPrice" class="price"><?php echo $this->getTierPriceHtml() ?></span>
	    	</p>
	    </div>
	    <div class="clear"> </div>
	     <script type="text/javascript">
			function displayLi(id,hideId)
			{
				document.getElementById(id).className = 'tabPanelContent';
				document.getElementById(id+'a').className = id+' tabSelected';
				document.getElementById(hideId).className = 'tabPanelContentHidden';
				document.getElementById(hideId+'a').className = hideId;
			}
		</script>
	    
	    <ul class="tabs">
	    	<li>
	    		<a id="familyOverviewa" class="familyOverview tabSelected" onclick="displayLi('familyOverview','familyReviews');" title="Overview">Overview</a>
	    	</li>
	    	<li>
	    		<a id="familyReviewsa" class="familyReviews" onclick="displayLi('familyReviews','familyOverview');" title="Related Products">Related Products</a>
	    	</li>
	    </ul>
	    
	    
	    <div id="familyOverview" class="tabPanelContent">
		    <div class="jScrollPaneContainer" style="height: 345px; width: 520px;">
		    	<div class="scroll-pane">
		    		<?php echo $this->getReviewsSummaryHtml($_product, false, false)?>
					<fieldset class="no-display">
						<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
						<input type="hidden" name="related_product" id="related-products-field" value="" />
					</fieldset>
					<?php echo $this->getChildHtml('alert_urls') ?>
					<?php echo $this->getChildHtml('product_type_data') ?>
	           		<?php if (!$this->hasOptions()):?>
						<div class="add-to-holder">
						    <?php if($_product->isSaleable()): ?>
						        <?php echo $this->getChildHtml('addtocart') ?>
						        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
						            <span class="add-or"><?php echo $this->__('OR') ?></span>
						        <?php endif; ?>
						    <?php endif; ?>
						    <?php echo $this->getChildHtml('addto') ?>
						</div>
					<?php else:?>
						<?php echo $this->getChildHtml('addto') ?>
					<?php endif; ?>
					<div class="divider"></div>
					<?php if ($_product->getShortDescription()):?>
						<br/>
							<p class="bold"><strong><?php echo $this->__('Quick Overview') ?></strong></p>
    						<div class="short-description"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
    						</div>
					<?php endif;?>
		           		<?php echo $this->getChildHtml('other');?>
		            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
						<?php echo $this->getChildChildHtml('container1', '', true, true) ?>
					<?php endif;?>
					<div class="clear"></div>
					<?php if ($_product->isSaleable() && $this->hasOptions()):?>
						<?php echo $this->getChildChildHtml('container2', '', true, true) ?>
					<?php endif;?>
					<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
					</form>
					<script type="text/javascript">
						var productAddToCartForm = new VarienForm('product_addtocart_form');
						productAddToCartForm.submit = function(){
						if (this.validator.validate()) {
						this.form.submit();
						}
						}.bind(productAddToCartForm);
					</script>
		    	</div>
		    </div>
		</div>
		<div id="familyReviews" class="tabPanelContentHidden">
			<div class="scroll-pane">				
				<?php echo $this->getChildHtml('upsell_products') ?>				
			</div>
		</div>
</form>
       