<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="price-box" id="product_price">
    <span class="old-price"><?php echo $this->__('Old Price:') ?> <?php echo $this->getPrice() ?></span><br />
    <span class="special-price"><?php echo $this->getPrice() ?></span>
</div>
