<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="block block-progress">
	<div class="block-title">
        <h3><?php echo $this->__('Your Checkout Progress') ?></h3>
     </div>
    <div class="block-content">   
    <dl>
    <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
    <?php if ($this->getCheckout()->getStepData('billing', 'complete')): ?>
        <dt class="complete">
            	<?php echo $this->__('Billing Address') ?> <a href="#billing" onclick="checkout.accordion.openSection('opc-billing'); return false;"><?php echo $this->__('Change') ?></a>
        </dt>
            <dd class="complete">
            <address><?php echo $this->getBilling()->format('html') ?></address>
            </dd>
        
    <?php else: ?>
       <dt><?php echo $this->__('Billing Address') ?></dt>
    <?php endif; ?>
    <?php endif; ?>
    <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
    <?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
         <dt class="complete">
        		<?php echo $this->__('Shipping Address') ?> <a href="#payment" onclick="checkout.accordion.openSection('opc-shipping');return false;"><?php echo $this->__('Change') ?></a></h4>
       	</dt>
        <dd class="complete">
            	<address>
                  <?php echo $this->getShipping()->format('html') ?>
                </address>
            </ul>
          </dd>
    <?php else: ?>
        <dt><?php echo $this->__('Shipping Address') ?></dt>
    <?php endif; ?>
    <?php endif; ?>
    <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
    <?php if ($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
         <dt class="complete">
        		<?php echo $this->__('Shipping Method') ?> <a href="#shipping_method" onclick="checkout.accordion.openSection('opc-shipping_method'); return false;"><?php echo $this->__('Change') ?></a></h4>
		</dt>
    	<dd class="complete">
         <?php if ($this->getShippingMethod()): ?>
             <a href="#"><?php echo $this->getShippingDescription(); ?></a>

            <?php $_excl = $this->getShippingPriceExclTax(); ?>
            <?php $_incl = $this->getShippingPriceInclTax(); ?>
            <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
               <a href="#"><?php echo $_incl; ?></a>
            <?php else: ?>
               <a href="#"><?php echo $_excl; ?></a>
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
            <?php endif; ?>

        <?php else: ?>
            <a href="#"><?php echo $this->__('Shipping method has not been selected yet') ?></a>
        <?php endif ?>
    	</dd>
    <?php else: ?>
       <dt><?php echo $this->__('Shipping Method') ?></dt>
    <?php endif; ?>
    <?php endif; ?>
    <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
    <?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
         <dt class="complete">	
    	<?php echo $this->__('Payment Method') ?> <a href="#payment" onclick="checkout.accordion.openSection('opc-payment');return false;"><?php echo $this->__('Change') ?></a>
       	</dt>
        <dd class="complete">
            <address><?php echo $this->getPaymentHtml() ?></address>
        </dd>
    <?php else: ?>
       <dt><?php echo $this->__('Payment Method') ?></dt>
    <?php endif; ?>
    <?php endif; ?>
    </dl>
</div>
</div>