<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<form id="co-shipping-method-form" action="">
<div class="inner-box">
    <div class="default-box" id="checkout-shipping-method-load">
        <?php echo $this->getChildHtml('available') ?>
    </div>
</div>
<script type="text/javascript">
    var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
</script>
<div id="onepage-checkout-shipping-method-additional-load">
<?php echo $this->getChildHtml('additional') ?>
</div>
</form>
<div class="inner-box">
    <div class="button-set no-border">
        <div id="shipping-method-buttons-container">            
        	<button type="button" class="form-button right" onclick="shippingMethod.save()"><span><?php echo $this->__('Continue') ?></span></button>
           &nbsp;
            <a href="#" onclick="checkout.back(); return false;"><?php echo $this->__('Back') ?></a>
            
            <span id="shipping-method-please-wait" style="display:none;" class="opc-please-wait">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
            </span>
        </div>
    </div>
</div>
