<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<?php $l=$this->getWishlist()->count() ?>
<div style="border:1px solid #bebcb7; padding:15px; background:#f8f7f5;">
<table cellspacing="0" cellpadding="0" border="0" width="100%">
    <tr>
    <?php $i=0; foreach($this->getWishlist() as $item): $i++ ?>
        <td width="32%">
            <p align="center"><a href="<?php echo $item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($item, 'small_image')->resize(135); ?>" style="border:1px solid #ccc;" width="135" alt="" /></a></p>
            <p align="center"><a href="<?php echo $item->getProductUrl() ?>" style="color:#203548;"><strong><?php echo $this->htmlEscape($item->getName()) ?></strong></a></p>
            <?php if($this->hasDescription($item)): ?><p align="center"><?php echo $this->__('Comment') ?>:<br /><?php echo $this->getEscapedDescription($item) ?></p><?php endif; ?>
            <p align="center"><a href="<?php echo $item->getProductUrl() ?>" style="color:#1E7EC8;"><?php echo $this->__('View Product') ?></a> <small><?php if($item->getIsSalable()):?>|</small> <a href="<?php echo $this->getUrl('checkout/cart/add', array('product'=>$item->getId())) ?>" style="color:#DC6809;"><strong><?php echo $this->__('Add to Cart') ?></strong></a><?php endif;?>
            </p></td>
        <?php if ($i%3!=0): ?>
            <td width="2%"></td>
        <?php else: ?>
           </tr>
            <tr>
                <td colspan="5">&nbsp;</td>
            </tr>
            <?php if ($i<$l): ?>
               <tr>
            <?php endif ?>
        <?php endif ?>
    <?php endforeach ?>
</table>
</div>
