<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="box layered-nav">
    <div class="head" >
        <h3><?php echo $this->__('My Account'); ?></h3>
    </div>
            <ul>
                <?php $_links = $this->getLinks(); ?>
                <?php $_index = 1; ?>
                <?php $_count = count($_links); ?>
                <?php foreach ($_links as $_link): ?>
                    <?php $_last = ($_index++ >= $_count); ?>
                    <?php if ($this->isActive($_link)): ?>
                        <li class="on<?php echo ($_last ? ' last' : '') ?>"><?php echo $_link->getLabel() ?></li>
                    <?php else: ?>
                        <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
</div>
<br/>