
<div id="bottomrail">
				<div class="bottomrail_1">
				<table cellspacing="0" cellpadding="0" border="0">
					<tbody><tr>
						<td width="5"/>
						<td>
						<h1>Sale!</h1>
						<a title="" href="#"><img hspace="3" border="0" align="left" vspace="2" alt="See Kai Run and Smaller Sale" valign="top" src="<?php echo $this->getSkinUrl('images/bottomrail_sale.jpg');?>"/></a><p class="smallfont">Select See Kai Run and Smaller styles on sale now.</p><p>
						</p><p class="smallfont"><a title="See Kai Run and Smaller Sale" href="#">Shop our sale items now</a>.</p>
						</td>
						<td width="5"> </td>
					</tr>
				</tbody></table>
				</div>
				<!--end of bottomrail_1-->
				<div class="bottomrail_2">
								<table cellspacing="0" cellpadding="0" border="0">
					<tbody><tr>
						<td width="5"> </td>
						<td>
						<h1>Free Shipping</h1>
						<p class="smallfont">Free ground shipping to US addresses with minimum $60 purchase.</p> 
						<p class="smallfont"><a title="See Kai Run shipping information" href="#">Click here for more details.</a></p>

						</td>
						<td width="5"> </td>
					</tr>
				</tbody></table>
				</div>
				<!--end of bottomrail_2"-->
				<div class="bottomrail_3">
				<table cellspacing="0" cellpadding="0" border="0">
					<tbody><tr>
						<td width="5"> </td>
						<td>
						<h1>Need Shoes Now?</h1>
						<p class="smallfont">Check out our <a title="See Kai Run store finder" href="#">store finder</a> for the See Kai Run retailer nearest you.</p>
						<p class="smallfont">Please call ahead to confirm availability.</p>
						</td>
						<td width="5"> </td>
					</tr>
				</tbody></table>
				</div>
				<!--end of bottomrail_4"-->
								<div class="bottomrail_4">
				<table cellspacing="0" cellpadding="0" border="0">
					<tbody><tr>
						<td width="5"/>
						<td>
							<h1 align="left">Join Us!</h1>
							<p><a href="#"><img alt="Sign up for the See Kai Run e-mail newsletter" src="<?php echo $this->getSkinUrl('/images/signup_for_skr_email.gif');?>"/></a></p>
							<p><a target="_blank" href="#"><img alt="Become a See Kai Run fan on Facebook" src="
<?php echo $this->getSkinUrl('/images/join_skr_facebook.gif');?>"/></a></p>
							<a target="_blank" href="#"><img alt="Follow See Kai Run on Twitter" src="<?php echo $this->getSkinUrl('/images/follow_skr_twitter.gif');?>"/></a>

							</td>
							<td width="5"> </td>
						</tr>
					</tbody></table>
				</div>
				<!--end of bottomrail_4"-->
			</div>
