<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>

<?php echo $this->getChildHtml() ?>
<br /><br />
<div class="copyright"><div style="float:left; margin-top: 15px;">Copyright &copy 2010 - 2011. All Rights Reserved. Designed by <a href="http://www.magentomagik.com/" target="_blank">MagentoMagik.com</a></div>
<div style="float:right; margin-right: 20px;"><a href="http://www.magentomagik.com/themes.html" target="_blank">Magento Themes </a>&nbsp;&nbsp;<a href="http://www.magentomagik.com/extensions.html" target="_blank">Magento Extensions</a>&nbsp;&nbsp;<a href="http://www.magentomagik.com/service-packs.html" target="_blank">Magento Custom Development</a></div></div>

