<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
/**
 * This template is for generic wrapper purposes, including ajax.updater loaded blocks
 *
 * Usage in layout xml files:
 * <block type="core/template" template="page/html/wrapper.phtml">
 *    <action method="setId"><id>some-custom-identificator</id></action>
 *
 *    <!-- optional -->
 *    <action method="setTag"><tag>span</tag></action> <!-- div is used if not specified -->
 *    <action method="setParams"><params>class="custom-class"</params></action>
 *
 *    <!-- insert wrapped blocks here -->
 * </block>
 */
?>
<?php $_tag = $this->hasTag() ? $this->getTag() : "div" ?>
<<?php echo $_tag?> id="<?php echo $this->getId()?>" <?php echo $this->getParams()?>>
<?php echo $this->getChildHtml()?>
</<?php echo $_tag?>>