<?php
/**
 * Theme:   Beadsjewellery
 * Author:  Attila Fabrik
 * Version: 1.5
 * Source:  http://www.beadsjewellery.co.uk/
 **/
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body class="page-popup<?php echo !$this->getBodyClass()?' '.$this->getBodyClass():'' ?>">
<div class="page-print">
    <div class="print-head">
        <img src="<?php echo $this->getPrintLogoUrl() ? $this->getPrintLogoUrl() : $this->getSkinUrl('images/logo.png') ?>" alt="" />
        <!-- <div style="font-size:22px;">Beads <span style="color:#e56991; font-weight:bold;">Jewellery</span></div> -->
        <?php if ($this->getPrintLogoText()):?>
            <address><?php echo nl2br($this->htmlEscape($this->getPrintLogoText())) ?></address>
        <?php endif;?>
    </div>
    <?php echo $this->getChildHtml('content') ?>
    <div class="button-set">
        <button onclick="window.close();" class="form-button"><span><?php echo $this->__('Close Window') ?></span></button>
    </div>
    <?php echo $this->getAbsoluteFooter() ?>
</div>
</body>
</html>
