<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="box base-mini mini-compare-products">
<div class="borderClass" style="width: 190px;">
    <div class="head">
        <h4><span><?php echo $this->__('Recently Compared Products') ?></span></h4>
    </div>
    <div class="content">
        <ol id="recently-compared-items">
        <?php foreach ($_products as $_item): ?>
            <li><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></li>
        <?php endforeach; ?>
        </ol>
    </div>
    <script type="text/javascript">decorateList('recently-compared-items');</script>
</div>
</div>
<?php endif; ?>