<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
    <div class="page-head">
        <h2><?php echo $this->__('Forgot Your Password?') ?></h2>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
        <p><?php echo $this->__('Please enter your email below and we\'ll send you a new password.') ?></p>
        <div class="input-box">
           <label for="email_address"><?php echo $this->__('Email Address') ?></label> <span class="required">*</span><br>
           <input name="email" alt="email" type="text" id="email_address" class="required-entry validate-email input-text" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
        </div>
        <br/>
        <div class="button-set">
        	
        	<button type="submit" class="form-button"><span><?php  echo $this->__('Save') ?></span></button>
        	<a href="<?php echo $this->helper('customer')->getLoginUrl() ?>" class="">&laquo; <?php echo $this->__('Back to Login') ?></a>
    	</div>
    	
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
    //]]>
    </script>
