<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-head">
    <h2><?php echo $this->__('Newsletter Subscription') ?></h2>
</div>
<div class="">
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
    <fieldset>
        <?php echo $this->getBlockHtml('formkey')?>
        <div class="">
        	<input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"
			<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif ?> /> 
        		<span><?php echo $this->__('General Subscription') ?></span>
        </div>
    </fieldset>
    <div class="button-set">
    	
    	 <button type="submit" class="form-button"><span><?php echo $this->__('Save') ?></span></button>&nbsp;
    	 <a href="<?php echo $this->getBackUrl() ?>">&laquo; <?php echo $this->__('Back') ?></a>
      
    </div>
    
    
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
</div>
