<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/


/**
 * Downloadable product links
 *
 * @see Mage_Downloadable_Block_Catalog_Product_Samples
 */
?>

<?php if ($this->hasSamples()): ?>
    <dl class="item-options">
        <dt><?php echo $this->getSamplesTitle() ?></dt>
        <?php $_samples = $this->getSamples() ?>
        <?php foreach ($_samples as $_sample): ?>
            <dd>
                <a href="<?php echo $this->getSampleUrl($_sample) ?>" <?php echo $this->getIsOpenInNewWindow()?'onclick="this.target=\'_blank\'"':''; ?>><?php echo $_sample->getTitle() ?></a>
            </dd>
        <?php endforeach; ?>
    </dl>
<?php endif; ?>
