<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<br/><div style="padding-right:10px;padding-top:10px;"><a href="<?php echo $this->getCheckoutUrl()?>"><big><strong><?php echo Mage::helper('checkout')->__('Checkout with Multiple Addresses');?></strong></big></a></div>