<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="page-head">
    <h2><?php echo $this->__('Order Success') ?></h2>
</div>
<div class="content-box">
    <p><strong><?php echo $this->__('Thank you for your purchase!') ?></strong></p>
    <p><?php echo $this->__('We are processing your order and you will soon receive an email with details of the order. Once the order has shipped you will receive another email with a link to track its progress.') ?></p>
    <?php if($_orderIds = $this->getOrderIds()): ?>
        <?php $flag = false ?>
        <?php echo $this->__('Your order number is ') ?>
        <?php foreach ($_orderIds as $orderId=>$incrementId): ?>
            <?php if ($flag): ?>
                <?php echo ', ' ?>
            <?php endif; ?>
            <?php $flag = true ?>
            <a href="<?php echo $this->getViewOrderUrl($orderId) ?>"><?php echo $incrementId ?></a>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php echo $this->getChildHtml() ?>
</div>
<div class="button-set">
    <button type="button" class="form-button" onclick="setLocation('<?php echo $this->getContinueUrl() ?>')"><span><?php echo $this->__('Continue Shopping') ?></span></button>
</div>
