<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="col-2">
    <div class="head">
        <h5><?php echo $this->__('Newsletters') ?></h5>
        <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit Newsletters') ?></a>
    </div>
    <p><?php echo $this->__('You are currently subscribed to our newsletter.') ?></p>
</div>
