<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="page-head">
    <h2><?php echo $this->getTitle() ?></h2>
</div>
<div class="a-right">
    <?php echo $this->getChildHtml('links') ?>
</div>
<br />
<?php echo $this->getChildHtml('pager_top') ?>
<?php echo $this->getChildHtml('sitemap') ?>
<?php echo $this->getChildHtml('pager_bottom') ?>
