<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php if($this->getItemCount()): ?>
<div class="col-1 upsell">
    <h4><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h4>
    <ul class="generic-product-list">
    <?php foreach ($this->getItems() as $_item): ?>
        <li>
            <a href="<?php echo $_item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(75); ?>" width="75" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image" /></a>
            <div class="product-shop">
                <h5><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h5>
                <?php echo $this->getPriceHtml($_item, true) ?>
                <button class="form-button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')" type="button"><span><?php echo $this->__('Add to Cart') ?></span></button><br/>
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <small><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-cart"><?php echo $this->__('Add to Wishlist') ?></a></small>
                <?php endif; ?>
                <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?><br/>
                <small><a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></small>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
