<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/

/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */
?>
<div class="box base-mini mini-cart">
<div class="borderClass" style="width:190px;">
    <div class="head">
        <?php $_cartQty = $this->getSummaryCount() ?>
        <h3><?php echo $this->__('My Cart') ?></h3>
        <?php if ($_cartQty>0): ?>
            <?php if ($_cartQty==1): ?>
                <?php echo $this->__('There is <a href="%s"><strong>1 item</strong></a> in your cart.', $this->getUrl('checkout/cart')) ?>
            <?php else: ?>
                <?php echo $this->__('There are <a href="%s"><strong>%s items</strong></a> in your cart.', $this->getUrl('checkout/cart'), $_cartQty) ?>
            <?php endif ?>
            <p class="subtotal">
                <?php echo $this->__('Cart Subtotal:') ?> <strong><?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></strong>
                <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                    <br />(<strong><?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?></strong> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                <?php endif; ?>
            </p>
        <?php endif ?>
    </div>

    <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
    <div class="actions">
    <input type="image" src="<?php echo $this->getSkinUrl('images/checkout_button.png'); ?>" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')">
       
    </div>
    <?php endif ?>

    <?php $_items = $this->getRecentItems() ?>
    <?php if(count($_items)): ?>
    <div class="head">
    <h5><?php echo $this->__('Recently added item(s)') ?></h5>
    </div>
    <ol id="cart-sidebar">
    <?php foreach($_items as $_item): ?>
        <?php echo $this->getItemHtml($_item) ?>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('cart-sidebar', 'non-recursive')</script>
    <?php else: ?>
    <div class="content"><p><?php echo $this->__('You have no items in your shopping cart.') ?></p></div>
    <?php endif ?>
</div>
</div>
<!-- [ends] .cart-sidebar // -->