<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 */
?>
<p class="subTotal">
	<?php echo $this->renderTotals('footer'); ?>
</p>
<p class="shippingTotal">
	<?php echo $this->renderTotals(); ?>
</p>

