<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="page-head">
    <h2><?php echo $this->__('Share Your Wishlist') ?></h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSendUrl() ?>" id="form-validate" method="post">
<?php echo $this->getBlockHtml('formkey')?>
<fieldset class="group-select">
    <h4 class="legend"><?php echo $this->__('Sharing Information') ?></h4>
    <ul class="form-list">
        <li>
            <label for="email_address"><?php echo $this->__('Email addresses, separated by commas') ?> <span class="required">*</span></label><br/>
            <textarea name="emails" cols="60" rows="5" class="validate-emails required-entry"><?php echo $this->getEnteredData('emails') ?></textarea>
        </li>
        <li>
            <label for="message"><?php echo $this->__('Message') ?></label><br/>
            <textarea id="message" name="message" cols="60" rows="5"><?php echo $this->getEnteredData('message') ?></textarea>
        </li>
        <?php if($this->helper('wishlist')->isRssAllow()): ?>
        <li>
            <input type="checkbox" name="rss_url" id="rss_url" value="1" />
            <label for="rss_url"><?php echo $this->__('Check this checkbox if you want to add a link to an rss feed to your wishlist.') ?></label>
        </li>
        <?php endif; ?>
    </ul>
</fieldset>
<div class="button-set">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>  
    <button type="submit" class="form-button"><span><?php echo $this->__('Share Wishlist') ?></span></button>&nbsp;
    <a href="<?php echo $this->getUrl('*/')?>">&laquo; <?php echo $this->__('Back')?></a>
</div>
</form>
<script type="text/javascript">
//<![CDATA[
Validation.addAllThese([
    ['validate-emails', '<?php echo $this->__('Please enter a valid email addresses, separated by commas. For example johndoe@domain.com, johnsmith@domain.com.') ?>', function (v) {
                if(Validation.get('IsEmpty').test(v)) {
                    return true;
                }

                var valid_regexp = /^[a-z0-9\._-]{1,30}@([a-z0-9_-]{1,30}\.){1,5}[a-z]{2,4}$/i;
                var emails = v.split(',');

                for (var i=0; i<emails.length; i++) {
                    if(!valid_regexp.test(emails[i].strip())) {
                        return false;
                    }
                }

                return true;
            }]
]);
var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
