<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="page-head">
    <h3><?php echo $this->htmlEscape($this->getHeader()) ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if($this->getWishlist()->getSize()): ?>
<form action="<?php echo $this->getUrl('*/*/update') ?>" method="post">
    <table cellspacing="0" width="100%" class="data-table box-table" id="wishlist-table">
    <col width="130" />
    <col />
    <col width="130" />
    <thead>
        <tr>
            <th class="align-left"><?php echo $this->__('Product') ?></th>
            <th class="align-center"><?php echo $this->__('Comment') ?></th>
            <th class="align-center">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->getWishlist() as $item): ?>
        <tr>
            <td>
                <div>
                    <a href="<?php echo $item->getProductUrl() ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($item, 'small_image')->resize(113); ?>" alt="<?php echo $this->htmlEscape($item->getName()) ?>" width="113" />
                    </a>
                </div>
                <div><a href="<?php echo $item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($item->getName()) ?>"><?php echo $this->htmlEscape($item->getName()) ?></a></div>
                <?php echo $this->getPriceHtml($item) ?>
            </td>
            <td class="align-center"><?php echo $this->getEscapedDescription($item) ?></td>
            <td class="align-center">
                <?php if($item->isSaleable()): ?>
                <a href="#" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($item) ?>');return false;" class="link-cart"><?php echo $this->__('Add to Cart') ?></a><br/>
                <?php endif;?>
                <a href="#" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($item) ?>');return false;" class="link-cart"><?php echo $this->__('Add to Wishlist') ?></a>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
    </table>
    <script type="text/javascript">decorateTable('wishlist-table')</script>
    <?php if($this->isSaleable()):?>
    <div class="button-set">
        <button onclick="setLocation('<?php echo $this->getUrl('*/*/allcart', array('_current'=>true)) ?>')" class="form-button-alt"  type="button"><span><?php echo $this->__('Add All to Cart') ?></span></button>&nbsp;
    </div>
    <?php endif;?>
</form>
<?php else: ?>
    <p><?php echo $this->__('Wishlist is empty now.') ?></p>
<?php endif ?>