<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<?php if ($this->helper('wishlist')->isAllow()) : ?>
<?php //if($this->getCanDisplayWishlist()): ?>
<div class="box base-mini mini-wishlist">
    <div class="head">
        <h4><?php echo $this->__('My Wishlist - <a href="%s">%d Item(s)</a>',
                $this->helper('wishlist')->getListUrl(),
                $this->helper('wishlist')->getItemCount()
            ) ?></h4>
        <h5><?php echo $this->__('Last Added Items') ?></h5>
    </div>
    <?php if($this->helper('wishlist')->getItemCount()>0): ?>
    <ol id="wishlist-sidebar">
     <?php foreach($this->getWishlistItems() as $_item): ?>
        <li>
            <div class="product-images">
                <a href="<?php echo $_item->getProductUrl() ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50); ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" width="50" height="50" />
                </a>
            </div>
            <div class="product-details">
                <a href="<?php echo $this->helper('wishlist')->getRemoveUrl($_item) ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the wishlist?') ?>');" class="widget-btn">
                    <img src="<?php echo $this->getSkinUrl('images/list_remove_btn.gif') ?>" alt="<?php echo $this->__('Remove Item') ?>" />
                </a>
                <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                <?php echo $this->getPriceHtml($_item) ?>
                <?php if($_item->isSaleable()): ?>
                <a href="<?php echo $this->helper('wishlist')->getAddToCartUrlBase64($_item) ?>" class="link-cart"><?php echo $this->__('Add to Cart') ?></a>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('wishlist-sidebar')</script>
    <?php else: ?>
    <div class="content"><p><?php echo $this->__('You have no items in your wishlist.') ?></p></div>
    <?php endif ?>
    <div class="actions"><a href="<?php echo $this->helper('wishlist')->getListUrl() ?>"><?php echo $this->__('Go to Wishlist') ?></a></div>
</div>
<?php endif ?>
