<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-head">
    <?php if($this->helper('wishlist')->isRssAllow() && $this->getWishlist()->getSize()): ?>
        <a href="<?php echo $this->helper('wishlist')->getRssUrl(); ?>" class="link-feed"><?php echo $this->__('RSS Feed') ?></a>
    <?php endif; ?>
    <h2><?php echo $this->__('My Wishlist') ?></h2>
</div>
<div class="">
<?php if($this->getWishlist()->getSize()): ?>
<form action="<?php echo $this->getUrl('*/*/update') ?>" method="post">
    <?php echo $this->getBlockHtml('formkey')?>
    <table cellspacing="0" width="100%" class="data-table box-table" id="wishlist-table">
    <col width="130" />
    <col width="300" />
    <col />
    <col />
        <thead>
            <tr>
                <th><?php echo $this->__('Product') ?></th>
                <th><?php echo $this->__('Comment') ?></th>
                <th><?php echo $this->__('Added On') ?></th>
                <th class="a-center">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->getWishlist() as $item): ?>
            <tr>
                <td>
                    <div><a href="<?php echo $item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($item, 'small_image')->resize(113, 113); ?>" alt="<?php echo $this->htmlEscape($item->getName()) ?>" width="113" /></a></div>
                    <div><a href="<?php echo $item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($item->getName()) ?>"><?php echo $this->htmlEscape($item->getName()) ?></a></div>
                    <?php echo $this->getPriceHtml($item) ?>
                </td>
                <td align="center">
                    <textarea name="description[<?php echo $item->getWishlistItemId() ?>]" rows="3" cols="3" style="width:95%;height:160px;" onfocus="focusComment(this)" onblur="focusComment(this)"><?php echo ( $this->getEscapedDescription($item) ) ? $this->getEscapedDescription($item) : $this->helper('wishlist')->defaultCommentString() ?></textarea>
                </td>
                <td valign="top">
                    <?php echo $this->getFormatedDate($item->getAddedAt()) ?>
                </td>
                <td class="a-center" valign="top">
                <?php if($item->isSaleable()): ?>
                    <a href="<?php echo $this->getItemAddToCartUrl($item) ?>" class="link-cart"><?php echo $this->__('Add to Cart') ?></a><br />
                <?php endif; ?>
                    <a href="<?php echo $this->getItemRemoveUrl($item) ?>" onclick="return confirmRemoveWishlistItem();" class="link-remove" ><?php echo $this->__('Remove Item') ?></a>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<script type="text/javascript">decorateTable('wishlist-table')</script>
    <div class="button-set">
    	
        <button  class="form-button-alt" type="button" onclick="setLocation('<?php echo $this->getUrl('*/*/share') ?>')"><span><?php echo $this->__('Share Wishlist') ?></span></button>&nbsp;      
        <?php if($this->isSaleable()):?>     
        <button onclick="setLocation('<?php echo $this->getUrl('*/*/allcart') ?>')" class="form-button-alt"  type="button"><span><?php echo $this->__('Add All to Cart') ?></span></button>
        <?php endif;?>
        <button type="submit" class="form-button" name="do"><span><?php echo $this->__('Update Wishlist') ?></span></button>
        
    </div>
</form>
<?php else: ?>
    <p><?php echo $this->__('You have no items in your wishlist.') ?></p>
<?php endif ?>
<div class="button-set">
    <a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>
</div>
<script type="text/javascript">
//<![CDATA[
function confirmRemoveWishlistItem() {
    return confirm('<?php echo $this->__('Are you sure you want to remove this product from your wishlist?') ?>');
}

function focusComment(obj) {
    if( obj.value == '<?php echo $this->__('Please, enter your comments...') ?>' ) {
        obj.value = '';
    } else if( obj.value == '' ) {
        obj.value = '<?php echo $this->__('Please, enter your comments...') ?>';
    }
}
//]]>
</script>
</div>
