<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="collateral-box up-sell">
    <div class="head"><h4><?php echo $this->__('You may also be interested in the following product(s)') ?></h4></div>
    <table cellspacing="0" class="generic-product-grid catalog-listing" id="upsell-product-table">
    <?php // $this->setColumnCount(4); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <tr>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <td>
                <p class="product-image"><a href="<?php echo $_link->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(125) ?>" width="125" height="125" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a></p>
                <h5><a href="<?php echo $_link->getProductUrl() ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h5>
                <?php echo $this->getPriceHtml($_link, true) ?>
                <?php echo $this->getReviewsSummaryHtml($_link) ?>
            </td>
            <?php else: ?>
            <td class="empty-product">&nbsp;</td>
            <?php endif; ?>
        <?php endfor; ?>
        </tr>
    <?php endfor; ?>
    </table>
    <script type="text/javascript">decorateTable('upsell-product-table')</script>
</div>
<?php else: ?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
	$categories =$_product->getCategoryCollection()->load();
    $mainProd= $_product->getId();
 ?>
<div class="up-sell">
	<?php 
		$productIds = array();
		if ($categories->count())
      	foreach ($categories as $_category)
		{
			$Cnt=0;
			$products = Mage::getResourceModel('catalog/product_collection')->addCategoryFilter($_category)->addAttributeToSelect('small_image');
			foreach ( $products as $productModel )
			{
				$_product = Mage::getModel('catalog/product')->load($productModel->getId());
				$width=100; $height=100;
				$_imageUrl =  $this->helper('catalog/image')->init($productModel, 'small_image')->resize($width, $height);
				
				if($mainProd!=$productModel->getId() && $Cnt++ < 3 && ((!in_array($productModel->getId(),$productIds))))
				{
	?>
					<div class="fourth related ">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $_imageUrl ?>" width="<?php echo $width ?>" height="<?php echo $height ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /><span class="title"><?php echo $this->htmlEscape($_product->getName()) ?></span><span><span class="regPrice"><?php echo $this->getPriceHtml($_product, true) ?></span></span></a>
                	</div>
	<?php
				}
				$productIds[$productModel->getId()] = $productModel->getId();
			} 
			
		}
	?>
	</tr>     
	</table>
    <script type="text/javascript">decorateTable('upsell-product-table')</script>
</div>
<?php endif ?>
