<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="page-head">
    <h3><?php echo $this->__('Edit Tag') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form id="addTagForm" action="<?php echo $this->getFormAction(); ?>"  method="post">
<fieldset class="group-select">
    <h4 class="legend"><?php echo $this->__('Tag Information') ?></h4>
    <ul>
        <li>
            <div class="input-box">
            <input type="text" class="input-text required-entry" style="width:300px;" name="productTagName" value="<?php echo $this->htmlEscape($this->getTag()->getName()) ?>" />
            </div>
        </li>
    </ul>
</fieldset>
<div class="button-set">
    <a href="<?php echo $this->getUrl('*/*/view/', array('tagId' => $this->getTag()->getTagId())) ?>" class="left">&laquo; <?php echo $this->__('Back to view Tag') ?></a>
    <button type="button" class="form-button" onclick="tagForm.submit();"><span><?php echo $this->__('Save Tag') ?></span></button>
</div>
</form>
<script type="text/javascript">
    var tagForm = new VarienForm('addTagForm');
</script>