<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="account-box ad-tags">
    <div class="head">
            <h4><?php echo $this->__('My Recent Tags') ?></h4>
            <a href="<?php echo $this->getAllTagsUrl() ?>"><?php echo $this->__('View All Tags') ?></a>
    </div>
    <div class="borderClass">
    <ol>
        <?php $iterator = 0 ?>
        <?php foreach( $this->getCollection()->getItems() as $_item ): ?>
            <li<?php if($iterator % 2 == 0): ?> class="odd"<?php else: ?> class="even"<?php endif; ?>>
                <div class="count"><?php echo ++$iterator ?></div>
                <div class="content">
                    <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a><br/>
                    <strong><?php echo $this->__('Tags:') ?></strong>
                        <?php $_i = 0; ?>
                        <?php foreach( $_item->getProductTags() as $_tag ): ?>
                            <a href="<?php echo $_tag->getViewTagUrl() ?>"><?php echo $this->htmlEscape($_tag->getName()) ?></a><?php if(++$_i != sizeof($_item->getProductTags()->getItems())): ?>,<?php endif; ?>
                        <?php endforeach; ?>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
    </div>
</div>
