<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="account-box">
    <div class="page-head">
        <h3><?php echo $this->__('My Tags') ?></h3>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <p>
        <?php echo $this->__('Tag Name: %s', $this->htmlEscape($this->getTagInfo()->getName())) ?>
        ( <a href="<?php echo $this->getTagInfo()->getEditTagUrl(); ?>"><small><?php echo $this->__('Edit Tag') ?></small></a>
        <span class="separator">|</span>
        <a href="<?php echo $this->getTagInfo()->getRemoveTagUrl(); ?>" onclick="return confirm('<?php echo $this->__('Are you sure you want to delete this tag?') ?>');"><small><?php echo $this->__('Delete Tag') ?></small></a> )
    </p>
    <?php echo $this->getToolbarHtml() ?>
    <table class="data-table box-table" id="my-tags-table" cellspacing="0">
    <?php if( sizeof($this->getMyProducts()) > 0 ): ?>
        <col width="100" />
        <col />
        <col width="75" />
        <tbody>
        <?php $iterator = 0 ?>
        <?php foreach($this->getMyProducts() as $_product): ?>
            <tr<?php if($iterator % 2 == 0): ?> class="odd"<?php $iterator++;endif; ?>>
                <td><a href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(100, 100); ?>" alt="" height="100" width="100" /></a></td>
                <td>
                    <h5><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h5>
                    <?php echo $this->getPriceHtml($_product) ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <p><?php echo $_product->getDescription() ?></p>
                </td>
                <td class="a-center">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" class="form-button" onclick="setLocation('<?php echo $this->getUrl('checkout/cart/add',array('product'=>$_product->getId())) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                    <?php endif; ?>
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <br /><a href="<?php echo $this->getUrl('wishlist/index/add',array('product'=>$_product->getId())) ?>"><?php echo $this->__('Add to Wishlist') ?></a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    <?php else: ?>
            <tr>
            <td><p><?php echo $this->__("Unable to find any products tagged with '%s' in the current store", $this->htmlEscape($this->getTagInfo()->getName()) ) ?></p></td>
            </tr>
    <?php endif; ?>
    </table>
    <script type="text/javascript">decorateTable('my-tags-table')</script>
    <?php echo $this->getToolbarHtml() ?>
    <div class="button-set a-left">
        <a href="<?php echo $this->getUrl('*/*/')?>">&laquo;<?php echo $this->__('Back to Tags List')?></a>
    </div>
</div>
