<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="page-head">
    <h3><?php echo Mage::helper('customer')->__("You're now Logged Out") ?></h3>
</div>
<p><?php echo Mage::helper('customer')->__('You have been successfully logged out and will be redirected to our homepage in 5 seconds.') ?></p>
<script type="text/javascript">
setTimeout(function(){ location.href = '<?php echo $this->getUrl() ?>'},5000);
</script>
