<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>

    <div class="head">
            <h3><?php echo $this->__('My Orders') ?></h3>
        </div>

<?php if($orders->getSize()): ?>
    <table cellspacing="0" width="100%" class="data-table" id="my-orders-table" >
        <thead>
            <tr>
                <th><?php echo $this->__('Order #') ?></th>
                <th><?php echo $this->__('Date') ?></th>
                <th class="a-right"><?php echo $this->__('Total') ?></th>
                <th class="a-center"><?php echo $this->__('Status') ?></th>
                <th ><?php echo $this->__('Details') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($orders as $order): ?>
            <tr>
                <td><?php echo $order->getRealOrderId() ?>&nbsp;</td>
                <td><?php echo date("D, j M, Y", strtotime($order->getCreatedAt())) ?>&nbsp;</td>
                <td class="a-right"><?php echo $order->getGrandTotal() ?>&nbsp;</td>
                <td class="a-center"><?php echo $order->getStatus() ?>&nbsp;</td>
                <td><a href="<?php echo $this->getUrl('customer/order/view', array('order'=>$order->getOrderId())) ?>"><?php echo $this->__('View Order') ?></a>&nbsp;</td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders yet.') ?></p>
<?php endif ?>
    <div class="buttons-container">
        <a href="<?php echo $this->getUrl('customer/account') ?>" class="float-left">&laquo; <?php echo $this->__('Back') ?></a>
    </div>