<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<h4 class="title"><a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->getProductName() ?></a></h4>
<!-- item custom options -->
<?php if ($_options = $this->getOptionList()):?>
<dl class="item-options">
    <?php foreach ($_options as $_option) : ?>
    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
    <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
    <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
        <?php if (isset($_formatedOptionValue['full_view'])): ?>
        <div class="truncated_full_value">
            <dl class="item-options">
                <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
                <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
            </dl>
        </div>
        <?php endif; ?>
    </dd>
    <?php endforeach; ?>
</dl>
<?php endif;?>
<!-- / -->