<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<?php
/**
 * @see Mage_Downloadable_Block_Customer_Products_List
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_items = $this->getItems(); ?>
<div class="page-head">
    <h2><?php echo Mage::helper('downloadable')->__('My Downloadable Products') ?></h2>
</div>
<div>
<?php echo $this->getChildHtml('pager'); ?>
<?php if(count($_items)): ?>
<table cellspacing="0" class="data-table" id="my-downloadable-products-table">
    <thead>
        <tr>
            <th><?php echo Mage::helper('downloadable')->__('Order #') ?></th>
            <th><?php echo Mage::helper('downloadable')->__('Date') ?></th>
            <th><?php echo Mage::helper('downloadable')->__('Title') ?></th>
            <th><?php echo Mage::helper('downloadable')->__('Status') ?></th>
            <th><?php echo Mage::helper('downloadable')->__('Remaining Downloads') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_items as $_item): ?>
            <tr>
                <td><a href="<?php echo $this->getOrderViewUrl($_item->getPurchased()->getOrderId()) ?>" title="<?php echo Mage::helper('downloadable')->__('View Order') ?>"><?php echo $_item->getPurchased()->getOrderIncrementId() ?></a></td>
                <td><?php echo $this->formatDate($_item->getPurchased()->getCreatedAt()) ?></td>
                <td><?php echo $_item->getPurchased()->getProductName() ?> - <a href="<?php echo $this->getDownloadUrl($_item) ?>" title="<?php echo Mage::helper('downloadable')->__('Start Download') ?>" <?php echo $this->getIsOpenInNewWindow()?'onclick="this.target=\'_blank\'"':''; ?>><?php echo $_item->getLinkTitle() ?></a></td>
                <td><em><?php echo ucfirst($_item->getStatus()) ?></em></td>
                <td><?php echo $this->getRemainingDownloads($_item) ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-downloadable-products-table')</script>
<?php else: ?>
    <p><?php echo Mage::helper('downloadable')->__('You have not purchased any downloadable products yet.'); ?></p>
<?php endif; ?>
<?php echo $this->getChildHtml('pager'); ?>
<div class="button-set">
    <a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>
</div>
</div>
