<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="page-head">
    <h3><?php echo $this->__('All Tags') ?></h3>
</div>
<div class="box base-mini mini-product-tags">
    <div class="content">
        <?php if( sizeof($this->getTags()) > 0 ): ?>
        <ul>
            <?php foreach ($this->getTags() as $_tag): ?>
                <li><a href="<?php echo $_tag->getTaggedProductsUrl() ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;"><?php echo $this->htmlEscape($_tag->getName()) ?></a></li>
            <?php endforeach; ?>
        </ul>
        <?php else: ?>
        <p class="a-center"><small><?php echo $this->__("Tags Aren't Available") ?></small></p>
        <?php endif; ?>
    </div>
</div>
