<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="head">
    <h4><?php echo $this->__('Product Tags') ?></h4>
</div>
    <?php if( $this->getCount() ): ?>
    <h5><?php echo $this->__('Other people marked this product with these tags:') ?></h5>
        <ul class="tags-list">
            <?php $_iterator = 0; ?>
            <?php foreach( $this->getTags() as $_tag ): ?>
                <li<?php if( 1 == ++$_iterator && $this->getCount() != 1 ): ?> class="first"<?php elseif($_iterator == $this->getCount()): ?> class="last"<?php endif; ?>><a href="<?php echo $_tag->getTaggedProductsUrl() ?>"><?php echo $this->htmlEscape($_tag->getName()) ?></a> (<?php echo $_tag->getPopularity() ?>)</li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
<h5><?php echo $this->__('Add Your Tags:') ?></h5>
<div class="add-tag-box">
    <form id="addTagForm" action="<?php echo $this->getFormAction(); ?>"  method="get">
        <div class="input-box">
            <input type="text" class="input-text required-entry" name="productTagName" />
        </div>
        <fieldset><button type="button" class="form-button-alt" onclick="submitTagForm()"><span><?php echo $this->__('Add Tags') ?></span></button></fieldset>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var addTagFormJs = new VarienForm('addTagForm');
        function submitTagForm(){
            if(addTagFormJs.validator.validate()) {
                addTagFormJs.form.submit();
            }
        }
    //]]>
    </script>
    <div class="clear"></div>
    <small><?php echo $this->__("Use spaces to separate tags. Use single quotes (') for phrases.") ?></small>
</div>