<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="box base-mini mini-product-tags">
    <div class="head">
        <h4><?php echo $this->__('Popular Tags'); ?></h4>
    </div>
    <div class="content">
    <ul>
        <?php foreach ($this->getTags() as $_tag): ?>
            <li><a href="<?php echo $_tag->getTaggedProductsUrl() ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;"><?php echo $this->htmlEscape($_tag->getName()) ?></a></li>
        <?php endforeach; ?>
    </ul>
    </div>
    <div class="actions">
        <a href="<?php echo $this->getUrl('tag/list') ?>"><small><?php echo $this->__('View All Tags') ?></small></a>
    </div>
</div>
