<?php
/**
 * Theme: Magik Jewellery
 * Author: MagentoMagik.com
 * Version: 1.5
 * URL: http://www.magentomagik.com/magento-themes/free-magento-themes/magik-jewellery-magento-theme/
 * Source: http://www.magentomagik.com/
 **/
?>
<div class="page-head">
    <h3><?php echo $this->__("Products tagged with '%s' (<a href='%s'>RSS</a>)", $query, '/tag/index/xml?tag='.$query) ?></h3>
</div>
<?php if (!empty($collection)) { ?>
<ol>
<?php foreach ($collection as $item) { ?>
    <li>
        <?php echo $item['name']; ?>
        <strong>Tags:</strong>
            <?php foreach ($item['tags'] as $tag) { ?>
                <a href="/tag/index/search?q=<?php echo $tag['tagname']; ?>"><?php echo $tag['tagname']; ?></a> 
            <?php } ?>
    </li>
<?php } ?>
</ol>
<?php } ?>
